<div class="text-center h-100 p-5">
    <form action="" method="post" class="form-signin col-5 mx-auto d-flex flex-column align-items-center">
        <input type="hidden" name="login">
        <img class="mb-4 rounded" src="https://picsum.photos/200" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Connexion</h1>        
        <input type="email" name="mail" id="inputEmail" class="form-control mb-2" placeholder="Email address" required autofocus>        
        <input type="password" name="pwd" id="inputPassword" class="form-control mb-2" placeholder="Password" required>
        <button class="btn btn-lg btn-primary d-block mb-2" type="submit">Sign in</button>
        <a href="?page=inscription">Pas encore de compte ?</a>
    </form>
</div>
