<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>    
    <?php if(isset($_SESSION['user'])){ require 'templates/header.php';} ?>
    <div class="container-fluid py-5">
        <div class="row">        
            <main class="col-lg-12 px-4">
                <!-- Le router va renvoyer indirectement la bonne vue avec les bonne datas en fonction de la requête get -->
                <?php $router = new router() ?>
            </main>
        </div>
    </div>

    <?php require 'templates/footer.php'; ?>
</body>

</html>