<?php $products = $updateModel->products[0] ?>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edition Produit <?= $products['name'] ?> :</h5>
            <form method="post" action="">
                <div class="form-group">
                    <label for="name">Nom du produit</label>
                    <input type="text" class="form-control" id="name" name="name" value="<?= $products['name'] ?>">
                </div>
                <div class="form-group">
                    <label for="price">Prix</label>
                    <input type="number" step="0.01" class="form-control" id="price" name="price" value="<?= $products['price'] ?>">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <input type="text" class="form-control" id="description" name="description" value="<?= $products['description'] ?>">
                </div>
                <div class="form-group">
                    <label for="quantity">Quantité</label>
                    <input type="number" class="form-control" id="quantity" name="quantity" value="<?= $products['quantity'] ?>">
                </div>
                <div class="form-group">
                    <label for="marque_id">Marque ID</label>
                    <input type="number" class="form-control" id="marque_id" name="marque_id" value="<?= $products['marque_id'] ?>">
                </div>
                <br>
                <button type="submit" class="btn btn-success" name="update">Valider</button>
                <a href="?page=admin" class="btn btn-danger" name="update">Annuler</a>
            </form>
        </div>
    </div>
</div>